plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/environments/**/*'
    - 'db/*schema.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  CountComments: false
  CountAsOne: [array, hash, heredoc, method_call]
  Exclude:
    - '**/config/routes.rb'
    - '**/config/routes/**/*'

Metrics/ClassLength:
  CountComments: false
  CountAsOne: [array, hash, heredoc, method_call]
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Max: 20
  CountComments: false
  CountAsOne: [array, hash, heredoc, method_call]
  Exclude:
    - 'db/migrate/**/*'

Metrics/ModuleLength:
  CountComments: false
  CountAsOne: [array, hash, heredoc, method_call]

Naming/PredicateMethod:
  AllowedMethods:
    - call
    - data
    - action

Naming/AccessorMethodName:
  Exclude:
    - 'app/datatables/**/*'

Lint/MissingSuper:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Metrics/AbcSize:
  Max: 21

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/SharedExamples:
  EnforcedStyle: symbol

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/VerifiedDoubles:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

RSpec/ScatteredSetup:
  Exclude:
    - spec/requests/api/**/*_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Style/Documentation:
  Enabled: false

Capybara/AmbiguousClick:
  Enabled: true

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: true

Performance/ChainArrayAllocation:
  Enabled: true

Performance/IoReadlines:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

RSpec/DescribedClassModuleWrapping:
  Enabled: true

RSpec/Pending:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: true

Rails/DefaultScope:
  Enabled: true

Rails/OrderById:
  Enabled: true

Rails/PluckId:
  Enabled: true

Rails/RequireDependency:
  Enabled: true

Rails/UnusedIgnoredColumns:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/ClassMethodsDefinitions:
  Enabled: true
  EnforcedStyle: self_class

Style/ImplicitRuntimeError:
  Enabled: true

Style/IpAddresses:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/StaticClass:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/TopLevelMethodDefinition:
  Enabled: true

Style/TrailingCommaInBlockArgs:
  Enabled: true
  EnforcedStyleForMultiline: no_comma
